use rand::RngExt;

const PARAGRAPHS: [&str; 10] = [
    // 1: Norwegian wood
    "Of course: the 'field well'. I have no idea whether there was such a well. It might have been an image or a sign that existed only inside Naoko, like all the other things she used to spin into existence inside her mind in those dark days. Once she had described it to me, though, I was never able to think of that meadow scene without the well. From that day forward, the image of a thing I had never laid eyes on became inseparably fused to the actual scene of the field that lay before me. I can describe the well in minute detail. It lay precisely on the border where the meadow ended and the woods began - a dark opening in the earth a yard across, hidden by grass. Nothing marked its perimeter - no fence, no stone curb (at least not one that rose above ground level). It was nothing but a hole, a wide-open mouth. The stones of its collar had been weathered and turned a strange muddy-white. They were cracked and chunks were missing, and a little green lizard slithered into an open seam. You could lean over the edge and peer down to see nothing.",
    "Located on a hill in the middle of the city with open views, the dormitory compound sat on a large quadrangle surrounded by a concrete wall. A huge, towering zelkova tree stood just inside the front gate. People said it was at least 150 years old. Standing at its base, you could look up and see nothing of the sky through its dense cover of green leaves. The paved path leading from the gate circumvented the tree and continued on long and straight across a broad quadrangle, two three story concrete dorm buildings facing each other on either side of the path. They were large with lots of windows and gave the impression of being either flats that had been converted into jails or jails that had been converted into flats. However there was nothing dirty about them, nor did they feel dark. You could hear radios playing through open windows, all of which had the same cream-coloured curtains that the sun could not fade. Beyond the two dormitories, the path led up to the entrance of a two-story common building, the first floor of which contained a dining hall and bathrooms, the second consisting of an auditorium, meeting rooms, and even guest rooms.",
    "When I did finally meet the one person in my world who had read Gatsby, he and I became friends because of it. His name was Nagasawa. He was two years older than me, and because he was doing legal studies at the prestigious Tokyo University, he was on the fast track to national leadership. We lived in the same dorm and knew each other only by sight, until one day when I was reading Gatsby in a sunny spot in the dining hall. He sat down next to me and asked what I was reading. When I told him, he asked if I was enjoying it. 'This is my third time,' I said, 'and every time I find something new that I like even more than the last.' 'This man says he has read The Great Gatsby three times,' he said as if to himself. 'Well, any friend of Gatsby is a friend of mine.' And so we became friends. This happened in October. The better I got to know Nagasawa, the stranger he seemed. I had met a lot of weird people in my day, but none as strange as Nagasawa. He was a far more voracious reader than me, but he made it a rule never to touch a book by any author who had not been dead at least 30 years.",
    "During the summer holidays the university called in the riot police. They broke down the barricades and arrested the students inside. This was nothing new. It's what all the students were doing at the time. The universities were not so easily 'dismantled'. Massive amounts of capital had been invested in them, and they were not about to dissolve just because a few students had gone wild. And in fact those students who had sealed off the campus had not wanted to dismantle the university either. All they had really wanted to do was shift the balance of power within the university structure, about which I couldn't have cared less. And so, when the strike was finally crushed, I felt nothing. I went to the campus in September expecting to find rubble. The place was untouched. The library's books had not been carted off, the tutors' offices had not been destroyed, the student affairs office had not been burned to the ground. I was thunderstruck. What the hell had they been doing behind the barricades? When the strike was defused and lectures started up again under police occupation, the first ones to take their seats in the classrooms were those arseholes who had led the strike. As if nothing had ever happened, they sat there taking notes and answering 'present' when the register was taken.",
    "In any case, I myself feel that I am far closer to recovery than I once was, and people here tell me this is true. This is the first time in a long while I have been able to sit down and calmly write a letter. The one I wrote you in July was something I had to squeeze out of me (though, to tell the truth, I don't remember what I wrote - was it terrible?), but this time I am very, very calm. Clean air, a quiet world cut off from the outside, a daily schedule for living, regular exercise: those are what I needed, it seems. How wonderful it is to be able to write someone a letter! To feel like conveying your thoughts to a person, to sit at your desk and pick up a pen, to put your thoughts into words like this is truly marvellous. Of course, once I do put them into words, I find I can only express a fraction of what I want to say, but that's all right. I'm happy just to be able to feel I want to write to someone. And so I am writing to you.",
    "I bought a ticket and went to a bookshop across the street for a map. Back in the waiting room, I studied the map to see if I could find exactly where the Ami Hostel was located. It turned out to be much farther into the mountains than I had imagined. The bus would have to cross several hills in its trek north, then turn around where the canyon road dead-ended and return to the city. My stop would be just before the end of the line. There was a footpath near the bus stop, according to Naoko, and if I followed it for 20 minutes I would reach Ami Hostel. No wonder it was such a quiet place, if it was that deep in the mountains! The bus pulled out with about 20 passengers aboard, following the Kamo River through the north end of Kyoto. The tightly packed city streets gave way to more sparse housing, then fields and vacant land. Black tile roofs and vinyl-sided greenhouses caught the early autumn sun and sent it back with a glare. When the bus entered the canyon, the driver began hauling the steering wheel this way and that to follow the twists and curves of the road, and I began to feel queasy.",
    "Stretched out, he looked like some tiny creature with a fatal wound. He lay on his side, limp, the drooping left arm inert, jabbed with an intravenous needle. He was a small, skinny man who gave the impression that he would only get smaller and thinner. A white bandage encircled his head, and his pasty white arms were dotted with the holes left by injections or intravenous drips. His half-open eyes stared at a fixed point in space, bloodshot spheres that twitched in our direction when we entered the room. For some ten seconds they stayed focused on us, then drifted back to that fixed point in space. You knew when you saw those eyes he was going to die soon. There was no sign of life in his flesh, just the barest trace of what had once been a life. His body was like a dilapidated old house from which all the fixtures and fittings have been removed, awaiting its final demolition. Around the dry lips clumps of whiskers sprouted like weeds. So, I thought, even after so much of a man's life force has been lost, his beard continues to grow.",
    // 2: Trainspotting
    "Choose Life. Choose a job. Choose a career. Choose a family. Choose a fucking big television, choose washing machines, cars, compact disc players and electrical tin openers. Choose good health, low cholesterol, and dental insurance. Choose fixed interest mortage repayments. Choose a starter home. Choose your friends. Choose leisurewear and matching luggage. Choose a three-piece suite on hire purchase in a range of fucking fabrics. Choose DIY and wondering who the fuck you are on a Sunday morning. Choose sitting on that couch watching mind-numbing, spirit-crushing game shows, stuffing fucking junk food into your mouth. Choose rotting away at the end of it all, pishing your last in a miserable home, nothing more than an embarrassment to the selfish, fucked up brats you spawned to replace yourself. Choose your future. Choose life… But why would I want to do a thing like that? I chose not to choose life. I chose somethin' else. And the reasons? There are no reasons. Who needs reasons when you've got heroin?",
    "It was Begbie who ensured he could never return. He had done what he wanted to do. He could now never go back to Leith, to Edinburgh, even to Scotland, ever again. There, he could not be anything other than he was. Now, free from them all, for good, he could be what he wanted to be. He'd stand or fall alone. This thought both terrified and excited him as he contemplated life in Amsterdam. Ah don't hate the English. They're just wankers. We are colonised by wankers. We can't even pick a decent, vibrant, healthy culture to be colonised by. No. We're ruled by effete arseholes. What does that make us? ::: They filed out into the cold night at closing time, heading for Begbie's place with a carry-out. They'd already spent twelve hours drinking and pontificating about Matty's life and his motivations. In truth, the more reflective of them realised, all their insights pooled and processed, did little to illuminate the cruel puzzle of it all. They were no wiser now than at the start.",
    // 3: Amelie
    "He is late. She can only see two explanations. 1 - he didn't get the photo. 2 - before he could assemble it, a gang of bank robbers took him hostage. The cops gave chase. They got away... but he caused a crash. When he came to, he'd lost his memory. An ex-con picked him up, mistook him for a fugitive, and shipped him to Istanbul. There he met some Afghan raiders who too him to steal some Russian warheads. But their truck hit a mine in Tajikistan. He survived, took to the hills, and became a Mujaheddin. She refuses to get upset for a guy who'll eat borscht all his life in a hat like a tea cozy. ::: Let me help you. Step down. Here we go! The drum major's widow! She's worn his coat since the day he died. The horse's head has lost an ear! That's the florist laughing. He has crinkly eyes. In the bakery window, lollipops. Smell that! They're giving out melon slices! Sugarplum, ice cream! We're passing the park butcher. Ham, 79 francs. Spareribs, 45! Now the cheese shop. Picadors are 13. Cabecaus 25. A baby's watching a dog that's watching the chickens. Now we're at the kiosk by the metro. I'll leave you here. Bye!",
];

pub fn sentence() -> String {
    let mut rng = rand::rng();
    let random_index = rng.random_range(0..PARAGRAPHS.len());

    return PARAGRAPHS[random_index].to_string();
}
